package middle;

public enum CrashPoint {
	IMMEDIATE,

	MW_BEFORE_SND_VOTE_REQ,
	MW_AFTER_SND_VOTE_REQ,
	MW_AFTER_RCV_SOME_VOTE_REPLY,
	MW_AFTER_RCV_ALL_VOTE_REPLY,
	MW_AFTER_VOTE_DECISION,
	MW_AFTER_SND_SOME_DECISION,
	MW_AFTER_SND_ALL_DECISION,

	RM_AFTER_RCV_VOTE_REQ,
	RM_AFTER_SND_VOTE_REPLY,
	RM_AFTER_RCV_VOTE_DECISION
}