package middle;

public enum CrashPoint {
	IMMEDIATE,						// 0
	
	MW_AFTER_SND_SOME_VOTE_REQ,		// 1
	MW_AFTER_RCV_ALL_VOTE_REPLY,	// 2
	MW_AFTER_VOTE_DECISION,			// 3
	MW_AFTER_SND_SOME_DECISION,		// 4
	MW_AFTER_SND_ALL_DECISION,		// 5

	RM_AFTER_RCV_VOTE_REQ,			// 6
	RM_AFTER_SND_VOTE_REPLY,		// 7
	RM_AFTER_RCV_VOTE_DECISION		// 8
}