package middle;

public enum Message {
	RM_RCV_VOTE_REQUEST,
	RM_VOTED_YES,
	RM_VOTED_NO,
	
	RM_RCV_COMMIT_REQUEST,
	RM_RCV_ABORT_REQUEST,
	RM_COMMIT_SUCCESS,
	RM_COMMIT_ABORTED,
	
	TM_START_PREPARE,
	TM_SENT_VOTE_REQUEST,
	TM_RCV_VOTE_NO,
	TM_RCV_VOTE_YES,
	TM_DECIDED_YES,
	TM_DECIDED_NO,
	
	TM_START_COMMIT,
	TM_START_ABORT,
	TM_SENT_COMMIT_REQUEST,
	TM_SENT_ABORT_REQUEST,
	TM_SENT_ALL_COMMIT_REQUESTS,
	TM_SENT_ALL_ABORT_REQUESTS,
	
	TM_TXN_COMPLETED	
}