package middle;

public enum Message {
	RM_RCV_COMMIT_REQUEST,
	RM_RCV_ABORT_REQUEST,
	RM_COMMIT_SUCCESS,
	RM_COMMIT_ABORTED, 
	TM_TXN_COMPLETE, 
	TM_COMMITS_SENT, 
	TM_DECISION_YES, 
	TM_COMMIT_SENT_RM, 
	TM_DECISION_NO, 
	TM_START_COMMIT, 
	TM_INVALID_COMMIT, 
	TM_INVALID_ABORT, 
	TM_START_ABORT, 
	TM_ABORT_SENT_RM, 
	TM_ABORTS_SENT, 
	TM_PREPARE, 
	TM_SENT_REQUEST_RM, 
	TM_REQUEST_RESPONSE_NO_RM, 
	TM_REQUEST_RESPONSE_YES_RM, 
	RM_VOTE_YES, 
	RM_VOTE_REQUEST_RCV, 
	RM_VOTE_NO
}